from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Any, Dict, List


LOG_DIR = Path('out/experience')


def _parse_window(window: str) -> float:
    """Return earliest timestamp (epoch seconds) included by window spec like '30d', '24h'."""
    window = (window or '').strip().lower()
    now = time.time()
    m = re.match(r"^(\d+)([smhdw])$", window or '')
    if not m:
        # default: 30 days
        return now - 30 * 86400
    n = int(m.group(1))
    unit = m.group(2)
    mult = {'s':1, 'm':60, 'h':3600, 'd':86400, 'w':604800}[unit]
    return now - n * mult


def _read_logs(window: str) -> List[Dict[str, Any]]:
    if not LOG_DIR.exists():
        return []
    cutoff = _parse_window(window)
    files = []
    for p in LOG_DIR.glob('log*.jsonl'):
        files.append(p)
    files = sorted(files)
    out: List[Dict[str, Any]] = []
    for f in files:
        try:
            for ln in f.read_text(encoding='utf-8', errors='ignore').splitlines():
                ln = ln.strip()
                if not ln:
                    continue
                try:
                    rec = json.loads(ln)
                except Exception:
                    continue
                try:
                    ts = float(rec.get('ts') or 0)
                except Exception:
                    ts = 0.0
                if ts and ts < cutoff:
                    continue
                out.append(rec)
        except Exception:
            continue
    return out


def summarize_from_logs(window: str = '30d') -> Dict[str, Any]:
    rows = _read_logs(window)
    successes = sum(1 for r in rows if r.get('outcome_success'))
    failures = sum(1 for r in rows if not r.get('outcome_success'))
    # Intent distribution
    intent_counts: Dict[str, int] = {}
    for r in rows:
        try:
            dec = r.get('parent_decision') or {}
            intent = (dec.get('intent') or 'unknown')
            intent_counts[intent] = intent_counts.get(intent, 0) + 1
        except Exception:
            continue
    # Experiments
    experiments: Dict[str, Dict[str, Any]] = {}
    for r in rows:
        try:
            exp = r.get('experiment') or {}
            name = (exp.get('name') or '').strip()
            arm = (exp.get('arm') or '').strip()
            if name and arm:
                m = experiments.setdefault(name, {})
                e = m.setdefault(arm, {'successes': 0, 'failures': 0, 'latency_ms': []})
                if r.get('outcome_success'):
                    e['successes'] += 1
                else:
                    e['failures'] += 1
                lat = r.get('latency_ms')
                if isinstance(lat, (int, float)) and float(lat) > 0:
                    e['latency_ms'].append(float(lat))
        except Exception:
            continue
    ex_out: Dict[str, Any] = {}
    for name, arms in experiments.items():
        arm_stats: Dict[str, Any] = {}
        for arm, st in arms.items():
            s = int(st['successes'])
            f = int(st['failures'])
            n = s + f
            sr = (s / n) if n > 0 else None
            lat = st.get('latency_ms') or []
            av = (sum(lat) / len(lat)) if lat else None
            arm_stats[arm] = {'success_rate': sr, 'n': n, 'avg_latency_ms': av}
        ex_out[name] = arm_stats
    return {
        'window': window,
        'records': len(rows),
        'successes': successes,
        'failures': failures,
        'intent_counts': intent_counts,
        'experiments': ex_out,
    }


def make_report(window: str = '30d') -> str:
    data = summarize_from_logs(window)
    lines: List[str] = []
    lines.append(f"# Nerion Learning Report ({data['window']})")
    lines.append("")
    lines.append(f"- Records: {data['records']} — ✅ {data['successes']} / ❌ {data['failures']}")
    # Intent table
    if data.get('intent_counts'):
        lines.append("- Intents:")
        for k, v in sorted(data['intent_counts'].items(), key=lambda kv: kv[1], reverse=True):
            lines.append(f"  - {k}: {v}")
    # Experiments section
    exps = data.get('experiments') or {}
    if exps:
        lines.append("")
        lines.append("## Experiments")
        for name, arms in exps.items():
            lines.append(f"### {name}")
            for arm, st in arms.items():
                sr = st.get('success_rate')
                n = st.get('n')
                av = st.get('avg_latency_ms')
                sr_s = 'NA' if sr is None else f"{sr:.2f}"
                av_s = 'NA' if av is None else f"{int(av)}ms"
                lines.append(f"- {arm}: sr={sr_s} n={n} lat={av_s}")
    lines.append("")
    lines.append("Generated by nerion learn export")
    return "\n".join(lines)

